//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRG.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NRG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.01,0
        ///0,0
        ///0,0
        ///0,0
        ///0.01,0
        ///0.01,0
        ///0.01,0
        ///0.02,-0.001
        ///0.026,-0.002
        ///0.026,-0.002
        ///0.034,-0.008
        ///0.036,-0.014
        ///0.036,-0.014
        ///0.037,-0.035
        ///0.037,-0.036
        ///0.037,-0.036
        ///0.037,-0.037
        ///0.037,-0.037
        ///0.036,-0.038
        ///0.036,-0.038
        ///0.035,-0.038
        ///0.035,-0.038
        ///0.035,-0.038
        ///0.017,-0.045
        ///0.016,-0.045
        ///0.015,-0.046
        ///0.015,-0.046
        ///0.014,-0.047
        ///0.013,-0.048
        ///0.013,-0.049
        ///0.012,-0.049
        ///0.012,-0.049
        ///0.012,-0.05
        ///0.012,-0.05
        ///0.012,-0.051
        ///0.012,-0.051
        ///0.012,-0.052
        ///0.012,-0.052
        ///0.012,-0.052
        ///0.01,-0.06
        ///0.009,- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rail {
            get {
                return ResourceManager.GetString("Rail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.3,2.738
        ///-1.3,2.738
        ///-1.3,1.41
        ///-1.3,1.41
        ///1.185,2.738
        ///1.185,2.738
        ///1.185,1.41
        ///1.185,1.41
        ///-0.394,3.499
        ///0.279,3.499
        ///0.402,4.155
        ///-0.538,4.155
        ///-0.358,2.842
        ///-0.358,3.294
        ///-0.29,3.361
        ///0.174,3.361
        ///0.241,3.294
        ///0.241,2.841
        ///-1.144,3.379
        ///-0.68,3.428
        ///-1.112,3.314
        ///-0.706,3.368
        ///1.029,3.379
        ///0.565,3.428
        ///0.997,3.314
        ///0.591,3.368
        ///-0.261,3.298
        ///0.145,3.298
        ///-1.481,3.258
        ///-1.4,3.258
        ///-1.4,3.258
        ///-1.4,3.436
        ///-1.4,3.436
        ///-1.481,3.436
        ///1.344,3.258
        ///1.263,3.258
        ///1.263,3.258
        ///1.263,3.436
        ///1.263,3.436
        ///1.344,3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Train {
            get {
                return ResourceManager.GetString("Train", resourceCulture);
            }
        }
    }
}
